import * as Icons from "lucide-react";

export const services = [
    {
      title: "SEO Optimization",
      description: "Improve your website's visibility on search engines with our expert SEO services.",
      plan: "$99 Plan",
      progress: 65,
      status: "Accepted",
      icon: Icons.Search,
    },
    {
      title: "Web Development",
      description: "Custom website development tailored to your business needs using the latest technologies.",
      plan: "$299 Plan",
      progress: 100,
      status: "Finished",
      icon: Icons.PanelsTopLeft,
    },
    {
      title: "Social Media Management",
      description: "Manage and grow your social media presence with our comprehensive management services.",
      plan: "$199 Plan",
      progress: 75,
      status: "Pending",
      icon: Icons.Speech,
    },
    {
      title: "Content Creation",
      description: "Engaging and high-quality content creation to attract and retain your target audience.",
      plan: "$149 Plan",
      progress: 40,
      status: "Rejected",
      icon: Icons.Edit3,
    },

    {
      title: "Email Marketing",
      description: "Effective email marketing campaigns to boost your customer engagement and sales.",
      plan: "$129 Plan",
      progress: 85,
      status: "Accepted",
      icon: Icons.Mail,
    },
    {
      title: "Graphic Design",
      description: "Creative graphic design services to enhance your brand identity and marketing materials.",
      plan: "$179 Plan",
      progress: 55,
      status: "Finished",
      icon: Icons.Paintbrush,
    },
    {
      title: "Pay-Per-Click Advertising",
      description: "Maximize your ROI with targeted pay-per-click advertising campaigns.",
      plan: "$249 Plan",
      progress: 80,
      status: "Accepted",
      icon: Icons.CreditCard,
    },  
    {
      title: "Video Production",
      description: "Professional video production services to create compelling visual content for your brand.",
      plan: "$399 Plan",
      progress: 30,
      status: "Pending",
      icon: Icons.Video,
    },
    // {
    //   title: "Mobile App Development",
    //   Description: "Custom mobile app development for iOS and Android platforms to reach your audience on the go.",
    //   plan: "$499 Plan",
    //   progress: 20,
    //   status: "Rejected",
    //   icon: Icons.Smartphone,
    // },
    // {
    //   title: "Analytics & Reporting",
    //   Description: "Comprehensive analytics and reporting services to track your marketing performance and make data-driven decisions.",
    //   plan: "$89 Plan",
    //   progress: 90,
    //   status: "Finished",
    //   icon: Icons.BarChart2,
    // }
  ];